### Autor válido
POST localhost:8080/autores
Content-Type: application/json

{
"nome": "Rodrigo Pereira",
"email": "rodrigo.desenv@gmail.com",
"descricao": "Author description"
}

### Email vazio

POST localhost:8080/autores
Content-Type: application/json

{
  "nome": "Rodrigo Pereira",
  "email": "",
  "descricao": "Author description"
}

### Email inválido

POST localhost:8080/autores
Content-Type: application/json

{
  "nome": "Rodrigo Pereira",
  "email": "rodrigo.desenv",
  "descricao": "Author description"
}





