GET localhost:8080/paises

###
GET localhost:8080/estados


###

###
GET http://localhost:8080/paises/1


###
POST localhost:8080/paises
Content-Type: application/json

{
    "nome": "Brasil"
}

###
POST localhost:8080/estados
Content-Type: application/json

{
    "nome": "Minas Gerais",
    "idPais": 1
}


